CREATE TABLE `LOCACAO` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `UNIDADE_RETIRADA_ID` INT NOT NULL,
  `DATA_RETIRADA` DATE NOT NULL,
  `CLIENTE_ID` INT NOT NULL,
  `UNIDADE_DEVOLUCAO_ID` INT NOT NULL,
  `DATA_DEVOLUCAO` DATE NULL,
  `KM_APOS_ALUGUEL` INT NOT NULL,
  `CARRO_ID` INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`),
  CONSTRAINT `CARRO_ID` FOREIGN KEY (`CARRO_ID`) REFERENCES `CARRO` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `CLIENTE_ID` FOREIGN KEY (`CLIENTE_ID`) REFERENCES `CLIENTE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `UNIDADE_DEVOLUCAO_ID` FOREIGN KEY (`UNIDADE_DEVOLUCAO_ID`) REFERENCES `UNIDADE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX `CARRO_ID` 
ON `LOCACAO` (
  `CARRO_ID` ASC
);
CREATE INDEX `CLIENTE_ID` 
ON `LOCACAO` (
  `CLIENTE_ID` ASC
);
CREATE INDEX `UNIDADE_DEVOLUCAO_ID` 
ON `LOCACAO` (
  `UNIDADE_DEVOLUCAO_ID` ASC
);

CREATE TABLE `CARRO` ( 
  `id` INT AUTO_INCREMENT NOT NULL,
  `CARACTERISTICAS_ID` INT NOT NULL,
  `STATUS` ENUM NOT NULL COMMENT 'enum(\'DISPONIVEL\',\'ALUGADO\',\'MANUTENCAO\')' ,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`id`),
  CONSTRAINT `CARACTERISTICAS_ID` FOREIGN KEY (`CARACTERISTICAS_ID`) REFERENCES `CARACTERISTICAS_CARRO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX `CARACTERISTICAS_ID` 
ON `CARRO` (
  `CARACTERISTICAS_ID` ASC
);

CREATE TABLE `CARACTERISTICAS_CARRO` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `VERSAO_ID` INT NOT NULL,
  `CATEGORIAS_ID` INT NOT NULL,
  `COR_ID` INT NOT NULL,
  `MONTADORA_ID` INT NOT NULL,
  `KM_ANTES_DO_ALUGUEL` INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`),
  CONSTRAINT `CATEGORIAS_ID` FOREIGN KEY (`CATEGORIAS_ID`) REFERENCES `CATEGORIAS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `COR_ID` FOREIGN KEY (`COR_ID`) REFERENCES `COR` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `MONTADORA_ID` FOREIGN KEY (`MONTADORA_ID`) REFERENCES `MONTADORA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `VERSAO_ID` FOREIGN KEY (`VERSAO_ID`) REFERENCES `VERSAO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX `CATEGORIAS_ID` 
ON `CARACTERISTICAS_CARRO` (
  `CATEGORIAS_ID` ASC
);
CREATE INDEX `COR_ID` 
ON `CARACTERISTICAS_CARRO` (
  `COR_ID` ASC
);
CREATE INDEX `MONTADORA_ID` 
ON `CARACTERISTICAS_CARRO` (
  `MONTADORA_ID` ASC
);
CREATE INDEX `VERSAO_ID` 
ON `CARACTERISTICAS_CARRO` (
  `VERSAO_ID` ASC
);
CREATE TABLE `VERSAO` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `NOME` VARCHAR(250) NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`)
);
CREATE TABLE `CATEGORIAS` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `OPCOES` ENUM NOT NULL COMMENT 'enum("HATCH","SEDAM COMPACTO","SEDAM MEDIO","SUV","PICAPES","CROSSOVER","PERUA","MINIVAN","ESPORTIVO","FURGAO")' ,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`)
);

CREATE TABLE `COR` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `OPCOES` ENUM NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`)
);

CREATE TABLE `MONTADORA` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `NOME` VARCHAR(250) NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`)
);

CREATE TABLE `CLIENTE` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `NOME` VARCHAR(250) NOT NULL,
  `CELULAR` VARCHAR(11) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `ENDERECO_ID` INT NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `STATUS_CLIENTE` ENUM NOT NULL COMMENT 'enum(\'DISPONIVEL\',\'INDISPONIVEL\')' ,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`),
  CONSTRAINT `ENDERECO_ID` FOREIGN KEY (`ENDERECO_ID`) REFERENCES `ENDERECO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX `ENDERECO_ID` 
ON `CLIENTE` (
  `ENDERECO_ID` ASC
);

CREATE TABLE `UNIDADE` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `NOME` VARCHAR(250) NOT NULL,
  `ENDERECO_ID` INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`),
  CONSTRAINT `ENDERECO_ID_UNIDADE` FOREIGN KEY (`ENDERECO_ID`) REFERENCES `ENDERECO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX `ENDERECO_ID_UNIDADE` 
ON `UNIDADE` (
  `ENDERECO_ID` ASC
);

CREATE TABLE `ENDERECO` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `NUMERO` INT NOT NULL,
  `RUA_ID` INT NOT NULL,
  `BAIRRO_ID` INT NOT NULL,
  `CIDADE_ID` INT NOT NULL,
  `ESTADO_ID` INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`),
  CONSTRAINT `FK_BAIRRO_ID` FOREIGN KEY (`BAIRRO_ID`) REFERENCES `BAIRRO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_CIDADE_ID` FOREIGN KEY (`CIDADE_ID`) REFERENCES `CIDADE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ESTADO_ID` FOREIGN KEY (`ESTADO_ID`) REFERENCES `ESTADO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_RUA_ID` FOREIGN KEY (`RUA_ID`) REFERENCES `RUA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX `FK_BAIRRO_ID` 
ON `ENDERECO` (
  `BAIRRO_ID` ASC
);
CREATE INDEX `FK_CIDADE_ID` 
ON `ENDERECO` (
  `CIDADE_ID` ASC
);
CREATE INDEX `FK_ESTADO_ID` 
ON `ENDERECO` (
  `ESTADO_ID` ASC
);
CREATE INDEX `FK_RUA_ID` 
ON `ENDERECO` (
  `RUA_ID` ASC
);

CREATE TABLE `RUA` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `NOME` VARCHAR(250) NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`)
);

CREATE TABLE `BAIRRO` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `NOME` VARCHAR(250) NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`)
);

CREATE TABLE `CIDADE` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `NOME` VARCHAR(250) NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`)
);

CREATE TABLE `ESTADO` ( 
  `ID` INT AUTO_INCREMENT NOT NULL,
  `NOME` VARCHAR(250) NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`ID`)
);
